apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ks
spec:
  ingressClassName: nginx
  rules:
    - host: ks-rhdm.your-domain.com
      http:
        paths:
          - backend:
              service:
                name: ks
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific
