apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    application: rhdm
  name: rhdm-svc-ac
---
apiVersion: v1
kind: RoleBinding
metadata:
  labels:
    application: rhdm
  name: rhdm-svc-ac-edit
roleRef:
  name: edit
subjects:
  - kind: ServiceAccount
    name: rhdm-svc-ac
