apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    application: rhdm
  name: rhdm-svc-ac
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    application: rhdm
  name: rhdm-svc-ac-view
roleRef:
  kind: Role 
  name: view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: rhdm-svc-ac
